Upgrade to TypeScript 4.4.4 (#278)
I did this:

    npm install --save-exact typescript@4.4

Then I got these errors when running `npm run build`:

    ERROR in /…/src/preferences-menu.tsx
    ./src/preferences-menu.tsx 51:9-28
    [tsl] ERROR in /…/src/preferences-menu.tsx(51,10)
          TS2304: Cannot find name 'EventHandlerNonNull'.

    ERROR in /…/src/operations/draft-mode-toggle.ts
    ./src/operations/draft-mode-toggle.ts 30:76-95
    [tsl] ERROR in /…/src/operations/draft-mode-toggle.ts(30,77)
          TS2304: Cannot find name 'EventHandlerNonNull'.

    ERROR in /…/src/operations/draft-mode-toggle.ts
    ./src/operations/draft-mode-toggle.ts 31:11-12
    [tsl] ERROR in /…/src/operations/draft-mode-toggle.ts(31,12)
          TS7006: Parameter '_' implicitly has an 'any' type.

    ERROR in /…/src/operations/improved-builtin-editing-tools-url.ts
    ./src/operations/improved-builtin-editing-tools-url.ts 71:15-18
    [tsl] ERROR in /…/src/operations/improved-builtin-editing-tools-url.ts(71,16)
          TS2571: Object is of type 'unknown'.

    ERROR in /…/src/operations/improved-builtin-editing-tools.ts
    ./src/operations/improved-builtin-editing-tools.ts 25:15-18
    [tsl] ERROR in /…/src/operations/improved-builtin-editing-tools.ts(25,16)
          TS2571: Object is of type 'unknown'.

I solved them like this:

  * `EventHandlerNonNull` was defined like this in TypeScript 4.3.5:

    ```typescript
    interface EventHandlerNonNull {
        (event: Event): any;
    }
    ```

    I replaced it with `(e: Event) => void`, which made sense for our use cases. That fixed the first three errors above.

  * TypeScript 4.4 [introduced the `useUnknownInCatchVariables` compiler option][useUnknownInCatchVariables], which defaults to `true` when `strict` is `true`. I used my trusty old `errorMessageFromCaught` utility function to fix the two resulting type errors.

[useUnknownInCatchVariables]: https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#defaulting-to-the-unknown-type-in-catch-variables-(--useunknownincatchvariables)

💡 `git show --color-words='4\.3\.5|\(\)|\w+|.'`