Upgrade to Jest 27 (#282)
I did this:

    npm install jest@27 @types/jest@27 ts-jest@27

Then `npm test` failed with this error:

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string. Consider using the "jsdom" test environment.

    ReferenceError: navigator is not defined

So I set the test environment to `"jsdom"`, just like in SimonAlling/userscripter#147.

Then `npm test` emitted this warning:

    ts-jest[main] (WARN) Replace any occurrences of "ts-jest/utils" with just "ts-jest".

So I did that.