Upgrade to Userscripter 3.0.0 (#265)
Today, an import like

    import * as build from "userscripter/build";

    void build;

in the run-time code (everything in `src/`) makes `npm run build` fail like this:

    ERROR in ./src/main.ts
    Module build failed (from ./node_modules/restrict-imports-loader/dist/index.js):
    Error: "userscripter/build" and its submodules cannot be imported in the source directory ('src'). Please remove these imports:
    
      • "userscripter/build", imported on line 3:
    
            import * as build from "userscripter/build";

With Userscripter 3.0.0, it instead fails with an unintelligible wall of text containing, among others, these errors:

  * `Critical dependency: require function is used in a way in which dependencies cannot be statically extracted`
  * `Critical dependency: the request of a dependency is an expression`
  * `Module not found: Error: Can't resolve 'fsevents' in '/home/alling/dev/better-sweclockers/node_modules/chokidar/lib'`
  * `System.import() is deprecated and will be removed soon. Use import() instead.`
  * `require.extensions is not supported by webpack. Use a loader instead.`
  * `Can't import the named export 'RawSource' from non EcmaScript module (only default export is available)`

That in itself is of course a downgrade, but I want to upgrade Userscripter as new versions are released unless there is a compelling reason not to.