Upgrade to Jest 28 (#283)
I did this, just like in SimonAlling/userscripter#149:

    npm install --save-dev --save-exact jest@28 @types/jest@28 ts-jest@28 jest-environment-jsdom@28

(`jest-environment-jsdom` [must be manually installed][jsdom] in Jest 28.)

Then `npm test` failed with this error:

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /…/node_modules/preact/dist/preact.module.js:1
    […]
    SyntaxError: Unexpected token 'export'

So I added `"preact"` to `DEPENDENCIES_TO_TRANSPILE`. Then `npm test` failed with this error:

    Invalid return value:
    `process()` or/and `processAsync()` method of code transformer found at
    "/…/__tests__/svgTransformer.js"
    should return an object or a Promise resolving to an object. The object
    must have `code` property with a string of processed code.
    This error may be caused by a breaking change in Jest 28:
    https://jestjs.io/docs/upgrading-to-jest28#transformer
    Code Transformation Documentation:
    https://jestjs.io/docs/code-transformation

So I modified the transformer [to return an object instead of a string][transformer].

[jsdom]: https://jest-archive-august-2023.netlify.app/docs/28.x/upgrading-to-jest28/#jsdom
[transformer]: https://jest-archive-august-2023.netlify.app/docs/28.x/upgrading-to-jest28/#transformer